bpsh 10 ./trace c1.txt cc1 < cc1.din
bpsh 10 ./trace c1.txt spice < spice.din
bpsh 10 ./trace c1.txt tex < tex.din
bpsh 10 ./trace c2.txt cc1 < cc1.din
bpsh 10 ./trace c2.txt spice < spice.din
bpsh 10 ./trace c2.txt tex < tex.din
bpsh 10 ./trace c3.txt cc1 < cc1.din
bpsh 10 ./trace c3.txt spice < spice.din
bpsh 10 ./trace c3.txt tex < tex.din
bpsh 10 ./trace c4.txt cc1 < cc1.din
bpsh 10 ./trace c4.txt spice < spice.din
bpsh 10 ./trace c4.txt tex < tex.din
bpsh 10 ./trace c5.txt cc1 < cc1.din
bpsh 10 ./trace c5.txt spice < spice.din
bpsh 10 ./trace c5.txt tex < tex.din
bpsh 10 ./trace c6.txt cc1 < cc1.din
bpsh 10 ./trace c6.txt spice < spice.din
bpsh 10 ./trace c6.txt tex < tex.din
bpsh 10 ./trace c7.txt cc1 < cc1.din
bpsh 10 ./trace c7.txt spice < spice.din
bpsh 10 ./trace c7.txt tex < tex.din
bpsh 10 ./trace c8.txt cc1 < cc1.din
bpsh 10 ./trace c8.txt spice < spice.din
bpsh 10 ./trace c8.txt tex < tex.din
bpsh 10 ./trace c9.txt cc1 < cc1.din
bpsh 10 ./trace c9.txt spice < spice.din
bpsh 10 ./trace c9.txt tex < tex.din
